name: EKS cluster destroy


on:
  workflow_dispatch:
    branches: [main]

jobs:
  destroy_cluster:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform destroy
        run: terraform destroy -auto-approve

