name: EKS cluster destroy


on:
  workflow_dispatch:
    branches: [main]

jobs:
  destroy_cluster:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Terraform init
        id: init
        run: terraform init -reconfigure

      - name: terraform destroy
        run: terraform destroy -auto-approve

